name: build_ErfanGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://public.by.files.1drv.com/y4mAhoVXe8GhHhqJ-Uj3i8J2mGZ-4qzbKYAeZwUfNB5xiEQR1ycXHgbYtzt0g9nt23csGp4zhwxYK9gIkNFJZCdTqB9FfYNkGmP-kDeuGbUpqoRPCRdzr0CVx-JY0khX010sybTWiq0tk7cke9UWoLMdijeAy0z4e0STbTdy048vqZWFtQZEroadKNc9AEMPyA12oro2b6IVQFF9r2LyNik_owMyqHyTemOoVB0JunErIQ?access_token=EwAAA61DBAAUmcDj0azQ5tf1lkBfAvHLBzXl5ugAAWvr2DFNsOrq7oJgb0XvF7vB2qLreWZ/l%2bk7LBLiuPfNI0nnLS4ExwzeGjrVsNF5z0qVdtg9BlTOVGXpbXM9SKDXAmEOyhhe0jayQ9wObo2A5YV3CaiaVY4LJkiOJ2fpaVci/Tza2fvtLYrifvEoS9myaPgN9uqpoa40z55kQrm5dhVKfa4WEWUchQvYVn54WhHaxxC0pWMrP2dOq1bo6Jctig1Trz%2bA9T5gilA9Upc2CbZFXYUzHW4CCBLppOw5P9iYOOMF%2bt0tacYpX3BIKaF2BGZv0jFY7KJufqjxTPXn8l1X%2bYowmGxpZJGSEoefBE6wt8X1lx6XrDUCQGes37IDZgAACLDsOaMuK9aZ0AFB/KrAuLJuoSREHxo8/eea6Blz7QEwB6x96xdiugL2EZmDUi79Lh681SE4EAak7m2Djo0zSySNFmLfzhcSrfk2bVAOwXUJ91kkW2ZE/lQIj6JI7alCfJlFi7plJ4qQezwn3ccm0Pa/lB8pMIV502d/O6ggtXd3FQ9KjmnZgzAfQMZQedJATgFa%2bkk5WgvDW5mCA6hgCkk3C09xSt5HOt/QWAr2OeKYr0ef9G%2b0FyWNL4NojRXy4/d1toh/gXG%2bQBA33Pd5L4x%2bUvTqNK0DeUfBDGXErbdWhjLxPIbVSnrKxHeBvDh7t4l2BA8AGzi...
  ROM_NAME: MIUI
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq install git wget
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git ErfanGSIs
         
       - name: Fix exit
         run: |
              sed -i 's/\|\| exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
              sed -i 's/exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
       
       - name: Setting up ErfanGSI requirements with Xiaoxin script
         run: |
              cd ErfanGSIs
              mkdir ./output
              wget https://raw.githubusercontent.com/TimeMapleLing/actions_build_SGSI/main/bin/setup.sh -o setup-xiaoxin.sh
              sudo bash setup-xiaoxin.sh
       
       - name: Download Stock Rom & Generate GSI
         run: sudo ./ErfanGSIs/url2GSI.sh -c -b $ROM_URL $ROM_NAME
       
       - name: Zip GSI  
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              mkdir final
              zip -r final/GSI.zip ./*
       
       - name: Upload GSI to WeTransfer
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet ./final/GSI.zip

         
            
